### ISSUE TITLE
Travis bug ! File is deleted but Travis flags ghost file as error.Where is the file located? 

### ISSUE THREAD

**Issue by zhihong8888** [nusCS2113-AY1819S1/forum#41] opened 2018-10-07 15:45 UTC
[T16-4] Centralised Human Resource System 
Link to Org repo: https://github.com/CS2113-AY1819S1-T16-4/main/tree/master/docs
Link to PR: nusCS2113-AY1819S1/addressbook-level4#4

My team has no idea why our Travis check failed "AboutUs.adoc" even after the whole file is deleted from our organization repo. 

We are 100% sure AboutUs.adoc doesn't have any problems with our organization repo check. But the school repo travis fails us.

We even tried 
my fork -> organization (passed travis) -> school (failed travis) 
my fork -> school (passed travis)

**Comment by okkhoy** [comment] 2018-10-08 04:21
I think the issue is same as described in #40; hence closing it. 
Reopen if the issue is different.

**Closed as completed by okkhoy** 2018-10-08 04:21 UTC
Labels: Question
